version: '3.4'

services:
  mongo-catalog-db:
    image: mongo
    container_name: mongo-catalog-db-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  redis-basket-cache:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  discount-db: # postgres
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer-container
    restart: always
    ports:
      - "4780:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  catalog.api:
    container_name: catalog.api-container
    build:
      context: .
      dockerfile: services/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongo-catalog-db-container:27017"
    depends_on:
      - mongo-catalog-db
    ports:
      - "4701:80"
  
  
  
  basket.api:
    container_name: basket.api-container
    build:
      context: .
      dockerfile: services/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redis-basket-cache-container:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc-container"
    depends_on:
      - redis-basket-cache
    ports:
      - "4702:80"
  
  discount.api:
    container_name: discount.api-container
    build:
      context: .
      dockerfile: services/Discount.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=postgres-container;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"

    depends_on:
      - discount-db
    ports:
      - "4703:80"
        
  discount.grpc:
    container_name: discount.grpc-container
    build:
      context: .
      dockerfile: services/Discount.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=postgres-container;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"

    depends_on:
      - discount-db
    ports:
      - "4704:80"

volumes:
  mongo_data:
  redis_data:
  portainer_data:
  postgres_data:
