version: '3.4'

services:
  mongo-catalog-db:
    image: mongo
    container_name: mongo-catalog-db-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  catalog.api:
    container_name: catalog.api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongo-catalog-db-container:27017"
    depends_on:
      - mongo-catalog-db
    ports:
      - "4701:80"

volumes:
  mongo_data: